<h1><a>Numerical and Scientific Computing</a></h1>

<h2><a id="index">Index</a></h2>

[1. Numpy Basics](#numpy)

[2. OpenCV](#opencv)

[3. Manipulations with Numpy](#numpyad)

[](#)

[](#)

<h2><a id="numpy">1. Numpy Basics</a></h2>

[Index](#index)

__Pandas__ is based on __numpy__. 

In [1]:
# 1D array in numpy
import numpy as np
n = np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [2]:
# 2D array
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [3]:
# 3D array
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
 m = np.asarray([[1, 2, 3], [4, 5, 6]])
print(m)

[[1 2 3]
 [4 5 6]]


<h2><a id="opencv">2. OpenCV</a></h2>

[Index](#index)

In [5]:
#!pip install opencv-python

In [6]:
import cv2

In [7]:
# Read Image in Grayscale
img = cv2.imread("smallgray.png", 0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
# Read image in color
img = cv2.imread("smallgray.png", 1)
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [9]:
# Write Back the image
cv2.imwrite("newsmallgray.png", img)

True

<h2><a id="numpyad">3. Manipulations with Numpy</a></h2>

[Index](#index)

In [10]:
img = cv2.imread("smallgray.png", 0)
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [11]:
img[2, 4]

182

In [12]:
# Iterating over the array
# This will print out the rows
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [13]:
# Iterate over columns
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [14]:
# To access each value, flatten the image
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [15]:
# Stacking two numpy arrays
# Horizental stack
ims = np.hstack((img, img))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
# Vertical Stack
ims = np.vstack((img, img))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
# Splitting an array (Horisental)
lst = np.hsplit(ims, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [18]:
# Splitting an array (Vertical)
lst = np.vsplit(ims, 3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]